name: ifcb-edi
channels:
 - conda-forge
dependencies:
- python=3
- scipy
- pandas
- h5py
- requests
- Pillow
- scikit-image
- pip
- r-base
- r-knitr
- r-taxize
- folium
- geopy
- ipykernel
- pip:
  - rectpack
  - pysmb
  - git+https://github.com/joefutrelle/pyifcb
